// Generated by `supabase gen types typescript`. Do not edit by hand.
// No business tables exist yet; the skeleton keeps the generic load bearing.
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
